### ISSUE TITLE
delete any scss code that has been duplicated into deprecated-component-library-helpers (breaking change)

### ISSUE THREAD

**Issue by mbylstra** [cultureamp/kaizen-design-system#1012]
This is the more ambitious follow up to https://github.com/cultureamp/kaizen-design-system/issues/1010 (just add deprecation warnings).

PR: https://github.com/cultureamp/kaizen-design-system/pull/1740

TODO
- [x] add a plugin for upgrading `@kaizen/component-library/style|layout|type.scss` imports, which defines some rules
- [x] preset imports the plugin and uses the rules

TODO (the actual plugin)
- [x] find usages of `@kaizen/component-library/styles/color|type|layout.scss`
- [x] replace with `@kaizen/deprecated-component-library-helpers/styles/color|type|layout.scss`
- [x] remove any duplicate `@kaizen/deprecated-component-library-helpers/styles/color|type|layout.scss` imports, making sure to keep the latest in the source code (to preserve any potential override behaviour)
- [x] write up how to use this (in the BREAKING CHANGE commit)

## Considerations:
If there are duplicate imports, and one is removed, could this cause a compilation error?
Eg:
```
@import "~@kaizen/component-library/styles/color";
@import "something.scss"
@import "~@kaizen/deprecated-component-library-helpers/styles/color";
```
would become
```
@import "something.scss"
@import "~@kaizen/deprecated-component-library-helpers/styles/color";
```
If "something.scss" is depending on `color.scss`, will this cause a compilation error (does the order of imports matter?)

**Comment by mbylstra** [comment]
Assessing impact or removing these files:

https://github.com/search?q=org%3Acultureamp+%22%40kaizen%2Fcomponent-library%2Fstyles%2Fcolor%22+extension%3Ascss&type=Code&ref=advsearch&l=&l=

**Comment by mbylstra** [comment]
I was hoping to be able to use github code search (limited to the cultureamp org) to find any imports to these files. However, it doesn't work as expected.

If I search for just "@kaizen/component-library" I get ~800 results (https://github.com/search?q=org%3Acultureamp+%22%40kaizen%2Fcomponent-library%22++extension%3Ascss&type=Code&ref=advsearch&l=&l=), but if I search for "@kaizen/component-library/styles/type" then I get 0 results, even though there are clearly lots of repos containing this.

What I realised just by searching "@kaizen/component-library" is that there are lots of repos using these files, so that question is already answered.

**Comment by mbylstra** [comment]
I think the next step for this is to release a codemod script that switches from the `@kaizen/component-library/styles/***` files to the identical `@kaizen/deprecated-component-library-helpers/styles/***` file. Changing the import is very simple. It's just (eg)
- replace `@kaizen/component-library/styles/type` with `@kaizen/deprecated-component-library-helpers/styles/type`

There are some extra complications though:
- The `@kaizen/deprecated-component-library-helpers` dependency needs to be added if it hasn't been. This could be a mono repo with multiple `package.json's`, so it would need to find the nearest package.json in the path (not assume it's at the root)
- there might be both an import for both `@cultureamp/component-library` and `@cultureamp/deprecated-component-library-helpers`, so when the first one is replace, not only is it wasted compilation time, it might throw a style lint error (duplicate import) and break the build. The earlier one should be deleted, as the second would have been overriding any previous styles (making the earlier one win might introduce regressions).

**Comment by mbylstra** [comment]
I tool that would be able to accurately search all repos in the Culture Amp repo (potentially including unreleased PRs) would be helpful for being able to pinpoint exactly which repos will be affected by breaking changes.

**Comment by ActuallyACat** [comment]
Depends on https://github.com/cultureamp/kaizen-design-system/pull/1520
