### ISSUE TITLE
Site relies on a timeout to make sure Storybook iframe content is loaded

### ISSUE THREAD

**Issue by sebpearce** [cultureamp/kaizen-design-system#102]
See https://github.com/cultureamp/kaizen-design-system/pull/84.

We need our Storybook demo iframe to adjust its height to match its content, since stories can vary a lot in size.

We can get the Storybook iframe to adjust its own height on its `onLoad` event, which is what everyone in internet land seems to suggest doing, but when we logged the `scrollHeight` (read: content height) of the iframe at `onLoad`, it was still 0. This suggests that Storybook is doing something after `onLoad` to load the stories.

The current solution is that when `onLoad` fires, we set a timeout of 1 second and _then_ adjust the height because the content will (hopefully!) have loaded by then.

@ActuallyACat and @sebpearce had a decent go at this, but couldn't find an event that was triggered _after_ the story had fully loaded. It would be much better to use such an event so we don't take a gamble on the content loading before the timeout happens.

**Comment by ActuallyACat** [comment]
Copy-paste from another convo:

The content of the iframe (disable your javascript and see this: https://cultureamp.design/storybook-static/iframe.html?id=button--label-icon) doesn’t send the browser any/much DOM or styles. So even though it’s “loaded” (i.e the initial content from the server is sent to the browser) there’s… not much there. So we’re getting the height of nothing, which is nothing. If we could look inside the iframe and check for a DOMContentLoaded event we would know if the dynamic stuff is rendered. In practice, no browsers support this.

Which leads me to say why you were right. You suggested sending an event from within the iframe to capture outside the iframe. This is the only solution I’ve found that works (unless we want to SSR everything):

https://stackoverflow.com/questions/24603580/how-can-i-access-the-dom-elements-within-an-iframe/24603642#comment38157462_24603642
Ideally, this would be refactored a little and abstracted out to its own little package
