### ISSUE TITLE
Deprecate add-tint, add-shade and add-alpha

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#1045]
These functions will soon be considered legacy. 

- [x] Remove all usages in Kaizen
- [ ] Add a style-lint plugin for warning about usages
- [x] Move the functions to `deprecated-helpers`

## add-tint and add-shade
`add-tint` and `add-alpha` is no longer encouraged. The Zen/Heart color palettes will accommodate the use cases where these were previously needed by using the next/previous color scale step. i.e take the following: 
```
.old-component {
  background-color: $seedling;
  &:hover {
    background-color: add-tint($seedling, 20%);
  }
}
``` 
this becomes
```
.old-component {
  background-color: $kz-color-seedling-400;
  &:hover {
    background-color: $kz-color-seedling-500;
  }
}
```

## add-alpha
Use `rgba()` to add transparency to a color, e.g. `rgba($kz-var-color-wisteria-800-rgb-params, 0.8)`.

**Comment by jasononeil** [comment]
After #1047 merged, there's still a few lingering places where `add-alpha` is not being used in Kaizen itself.

But we need to deprecate it. This is probably a style-lint plugin. I'll update the description to make that clear.

**Comment by lloydstubber** [comment]
Moved into discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1871)
