### ISSUE TITLE
fix `color-named` warnings coming from Kaizen

### ISSUE THREAD

**Issue by mbylstra** [cultureamp/kaizen-design-system#1049]
We are getting some noisy warnings from style lint that make it harder to notice when there are real issues:
```
packages/design-tokens/sass/color-vars.scss
 313:48  ⚠  Expected "#ffffff" to be "white"   color-named

packages/design-tokens/sass/color.scss
 48:18  ⚠  Expected "#ffffff" to be "white"   color-named
```

A couple of different ways to fix this:
A. turn off the style lint color warning.
B. update the tokens to use color names

**Comment by jasononeil** [comment]
Let's turn off the `color-named` rule

**Comment by mbylstra** [comment]
PR: https://github.com/cultureamp/kaizen-design-system/pull/1683
