### ISSUE TITLE
Fix warnings that are output in storybook compilation

### ISSUE THREAD

**Issue by mbylstra** [cultureamp/kaizen-design-system#1050]
There are tens of warnings of the following form which are noisy and make it difficult to notice other warnings/errors:

```
WARNING in ./draft-packages/tile/index.ts 4:0-88
"export 'TileAction' was not found in './KaizenDraft/Tile/components/GenericTile'
 @ ./draft-packages/tile/docs/Tile.stories.tsx
 @ ./draft-packages sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.tsx)$
 @ ./storybook/generated-stories-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server...
 ```
 
I've added the "quick win", but I'm not sure if it's actually a quick win or not or if there is something with our config that makes them impossible to avoid.

**Comment by mbylstra** [comment]
I did some research on this. I _think_ this is the relevant issue: https://github.com/babel/babel/issues/8361.

There are some workaround ideas people have posted:
https://github.com/babel/babel/issues/8361#issuecomment-547684460
https://github.com/babel/babel/issues/8361#issuecomment-577600016

... but I'm not sure we want to do `export * from xxxx` and the second idea sounds like a lot of work to do for every file.

Apparently this was fixed recently:
https://github.com/babel/babel/issues/8361#issuecomment-578317317 
https://github.com/babel/babel/pull/11171
And I believe we are on Typescript 4, so I think we already have `export type` support.

So, what I think we need to do is to do "barrel" types as separate `export type` statements. Eg 

```
export {
  AllowedTableHeaderBackgroundColors,
  TableCard,
  TableContainer,
  TableHeader,
  TableHeaderRow,
  TableHeaderRowCell,
  TableRow,
  TableRowCell,
} from "./Table"
```
would become
```
export {
  TableCard,
  TableContainer,
  TableHeader,
  TableHeaderRow,
  TableHeaderRowCell,
  TableRow,
  TableRowCell,
} from "./Table"

export type {
  AllowedTableHeaderBackgroundColors,
} from "./Table"

and that would remove the warning about `AllowedTableHeaderBackgroundColors` but still make the type declarations available for editors.

```

**Comment by mbylstra** [comment]
We are on at least Babel `7.12.9`, so we should be able to do it that way.

**Comment by mbylstra** [comment]
I'm trying this out in https://github.com/cultureamp/kaizen-design-system/pull/1691/files

**Comment by mbylstra** [comment]
I'm removing the quick win label because this approach is definitely not a quick win! Still might be worth it though, even if it means manually updating 100 files.

**Comment by mbylstra** [comment]
I might entertain the idea of writing a jscodeshift code mod for this. I think it's basically:
```
- for each index.ts
   - for each exported variable
      - find it in the imported file
         - if it starts with `export type`
            - the move it into the `export type` section of the index.ts
```
perhaps about a medium in terms of codemod complexity?
I'm wrapping up for the day, but I will check in in our next planning session.

**Comment by mbylstra** [comment]
worth mentioning: https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports

**Comment by ActuallyACat** [comment]
Can we update to typescript 3.8 so we can `export type ...`. Will this cause issues in Murmur / other <3.8 repos?
