### ISSUE TITLE
React Dropdown has become very difficult to automate

### ISSUE THREAD

**Issue by mbylstra** [cultureamp/kaizen-design-system#107]
We believe something has changed in the implementation of the Dropdown React component that broke an automation test.

The existing test was fixed with the following code:

from
```
          within('div[data-automation-id="xxxxxxxx"]') do
            find('div', text: '1000-2000').click
          end
```

to 

```
          within('div[data-automation-id="xxxxxxxx"]') do
            all('div', text: '1000-2000').last.click
          end
```
but it's strange that there are multiple elements with '1000-2000' - it used to be a simple `find` (find one). It shouldn't be that difficult to automation test.

I'm reporting on behalf of @jamesbarker.

**Comment by dougmacknz** [comment]
Closing as stale, especially with the `Dropdown` component now deprecated
