### ISSUE TITLE
Lots of broken links

### ISSUE THREAD

**Issue by dougmacknz** [cultureamp/kaizen-design-system#125]
The site has many links to other pages on the site which are broken. Eg. on the Buttons page - it tries to link to the 'Links vs Buttons' page via `/components/links-vs-button`, but the correct uri is `/guidelines/link-vs-button`.

I've created a PR which fixes some, but I haven't done a full audit so there's probably a bunch more.
https://github.com/cultureamp/kaizen-design-system/pull/124

Before we go any further - I just want to ask the question if there's any better way to fix this, to hopefully make this less likely to happen again in the future.

**Comment by ActuallyACat** [comment]
I've started keeping an eye out for these in Google Analytics. In the last month, we've had four 404 pages viewed: 
3 from /guidelines/mood (dead link from inline-notification page) 
1 from /guidelines/language (dead link from date-picker page) 

I'll open a PR to fix the dead links from the last month. Closing this PR for now as it's from a time where we had many dead links.
