### ISSUE TITLE
Menu Item icon is not changing colour when disabled

### ISSUE THREAD

**Issue by juliohr** [cultureamp/kaizen-design-system#1290]
The Menu component allows Menu items with icon + text.
When the the menu item is disabled, the text changes colour, but the icon remains the same.
The action can't be performed if you click on the icon, so we just need to fix the styles

```
<MenuItem
    action={() => {
      onSetAsDefault(comparison)
    }}
    label="Set as default"
    icon={settingsIcon}
    disabled={comparison.isDefault}
  />
```

![Slack___Threads___Culture_Amp](https://user-images.githubusercontent.com/995875/111939202-bd3bec00-8b1f-11eb-8e70-ebdc72c27b64.png)

**Comment by ActuallyACat** [comment]
Closed in https://github.com/cultureamp/kaizen-design-system/pull/1781
