### ISSUE TITLE
Container missing for ZenNavigationBar

### ISSUE THREAD

**Issue by makenosound** [cultureamp/kaizen-design-system#1310]
In implementing some stories for `ToastNotification` in https://github.com/cultureamp/kaizen-design-system/pull/758 I started pulling in the general page UI so that the stories have better context for developing the component (since its position matters in my PR).

In doing that I noticed that `ZenNavigationBar` doesn’t own the container that positions it, and so to implement it "correctly" I had to pull in the CSS from the `@cultureamp/navigation-bar-app` package that wraps things. You can see that in this commit: https://github.com/cultureamp/kaizen-design-system/pull/758/commits/e0ab6ace2f95bff5ad99143d0bcb3a5efdcac731

Wondering if there’s a particular reason for that separation? Or should we really be bringing the container _back_ into the `ZenNavigationBar` itself?

**Comment by dougmacknz** [comment]
This is a valid point, but I am going to close it 'cause we have deprecated `ZenNavigationBar` and are not expecting any more usages (`navigation-bar-app` + your toast stories are the only usages).
