### ISSUE TITLE
Well component - missing variants

### ISSUE THREAD

**Issue by ellisjas** [cultureamp/kaizen-design-system#1454]
## Missing stories / implementation of variants

* Informative borderless
* Positive dashed and borderless
* Negative dashed and borderless
* Cautionary dashed and borderless
* Assertive solid, dashed, and borderless
* Prominent solid, dashed, and borderless

## Figma design

https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit%3A-Heart?node-id=1929%3A14167

**Comment by ActuallyACat** [comment]
This could be split into a few different tickets - I would suggest whoever picks up this issue create a ticket/s for any outstanding missing variants if they can't fit everything into a pairing session.

**Comment by lloydstubber** [comment]
@ellisjas this is now fixed in this PR https://github.com/cultureamp/kaizen-design-system/pull/1939
