### ISSUE TITLE
Add type safety for Button component to prevent the consumer utilise badge and use icon on the right

### ISSUE THREAD

**Issue by martindavid** [cultureamp/kaizen-design-system#1534]
Investigate/implement types for the `Button` component to prevent a consumer of the component to use `badge` props along with `icon` on the right.

As we provide `badge` props to the `Button` component, it will look conflicted if we allow the consumer to also use the icon on the right (pending designer view).

Put a type-safe to the `Button` props that prevent the use of `badge` and `position="right"` at the same time.

**Comment by lloydstubber** [comment]
Moved into discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1870)
