### ISSUE TITLE
ToastNotification drops `onHide` prop and never calls back

### ISSUE THREAD

**Issue by OliBridgman** [cultureamp/kaizen-design-system#1545]
Hello, we're having an issue with the `ToastNotification` from `@kaizen/component-library` in performance-ui.
A recent upgrade has caused the notifications we save in state to now never disappear. The issue appears to be this commit: https://github.com/cultureamp/kaizen-design-system/commit/d84d8f4b5d1efd8340995bc6763dd57612f0ab37#diff-0c710c1332f581db3b3d144d2e6ba7c64240091f6526f198bd1d09bfca01e307
where `...otherProps` are being dropped and not passed through to the underlying components. The missing prop is the optional `onHide` callback, which is necessary for us to clear up old state.

We have a fix in our userland that removes our reliance on state cleanup and imports the newer API of this release, so we don't have to rely on this functionality anymore, but it may still be important for others that I am not aware of (I dunno who has bound their important business logic to a notification onHide callback but it's possible!). Even though this component has been deprecated, can we add the onHide callback back?

**Comment by KasiaMisirli** [comment]
well done @OliBridgman
