### ISSUE TITLE
Plan for uplifting the tile component

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#1709]
# About 
This issue is to create a plan for the new tile component. 

New design: https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit-Heart?node-id=16629%3A59090

Questions to answer: 
* Are we breaking the existing tile component?
* Are we keeping or dropping the flipping functionality? 
* API design 
* Is this codemoddable / can we automate the breaking change?
* Is this going to be used in a grid, or are we planning on building this in conjunction with a util which essentially acts as a container query. 
* Can we use a container query polyfil?
* etc

**Comment by lloydstubber** [comment]
Moved into discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1869)

**Comment by lloydstubber** [comment]
Moved into discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1869)
