### ISSUE TITLE
Draft modal breaks jest tests

### ISSUE THREAD

**Issue by ellisjas** [cultureamp/kaizen-design-system#1717]
When testing any component with the draft modal I get the error `TypeError: Cannot set property 'fillStyle' of null` which causes the test to fail.

I work around is to install `jest-canvas-mock` and add it to jest setup.

**Comment by ActuallyACat** [comment]
Thanks @ellisjas! The [breaking change in illustrations ](https://github.com/cultureamp/kaizen-design-system/blob/master/draft-packages/illustration/CHANGELOG.md#200-2021-06-09) looks to be the cause of this issue - modals were updated to use the latest version of illustrations so the mocks needed for that component need to be used in modals too.

I think we should come up with a solution to better manage the mocks needed to be setup in Kaizen (potentially through a different package).
