### ISSUE TITLE
Error thrown when trying to use --fix in @kaizen/stylelint-plugin

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#1746]
This is using stylelint-scss - I'm not sure why the repo is not using this as a plugin instead of invoking the config with `stylelint`. 

<img width="1293" alt="Screen Shot 2021-07-06 at 1 58 58 pm" src="https://user-images.githubusercontent.com/1621182/124540234-53dbb100-de62-11eb-951d-10862b0a87c1.png">

**Comment by jasononeil** [comment]
This is a problem with a 3rd party plugin, not the Kaizen plugin.

@mbylstra you might want to try disable 3rd party rules to help figure out what's the cause.
