### ISSUE TITLE
Some storybook decorators set styles that make it hard to understand how a component works

### ISSUE THREAD

**Issue by jasononeil** [cultureamp/kaizen-design-system#1750]
Because we are effectively using Storybook as developer documentation, it's important that the story code reflects how a component will work in reality.

Having a decorator like

```
    story => (
      <div style={{ display: "flex", justifyContent: "center" }}>{story()}</div>
    ),
  ],
```

hides an important part of the implementation from the story code, and therefore from the docs.

It would be better to remove these decorators, and either apply the necessary markup in the story, or have the story displayed without that markup.

To split this out into a couple of PRs, here's a list of component docs that need to be reviewed and updated: 
- [x] Avatar
- [x] Badge
- [x] Box
- [x] Button
- [x] Button / Icon button
- [x] Brand
- [x] Brand moment
- [x] Card
- [x] Collapsible
- [x] Divider
- [x] Empty state
- [x] Filter menu
- [x] Form / Checkbox field
- [x] Form / Checkbox group
- [x] Form / Radio field
- [x] Form / Radio group
- [x] Form / Select field
- [x] Form / Slider
- [x] Form / Text area field
- [x] Form / Text field
- [x] Form / Toggle switch field
- [x] Guidance block
- [x] Hero card
- [x] Hierarchical menu
- [x] Hierarchical select
- [x] Icon
- [x] Illustration
- [x] Likert scale
- [x] Loading placeholder
- [x] Loading spinner
- [x] Menu
- [x] Modal
- [x] Notification / Global
- [x] Notification / Inline
- [ ] Notification / Toast
- [x] Page layout / Content
- [x] Page layout / Skirt
- [x] Popover
- [x] Progress bar
- [x] Split button
- [x] Table
- [x] Tabs
- [x] Tag
- [x] Title block
- [x] Tooltip
- [x] Typography / Heading
- [x] Typography / Paragraph
- [x] Well

**Comment by makenosound** [comment]
Some well-named components we can use as wrappers in each story might work to solve this from both angles?

```
const CenterAndAllowChildrenToFlex = ...

<CenterAndAllowChildrenToFlex>
  <StoryCode />
</CenterAndAllowChildrenToFlex>
```

This one probably isn’t the clearest example, but you get the idea.

**Comment by OliBridgman** [comment]
I was just gonna delete em all @makenosound. Rip that bandaid off! :P

**Comment by makenosound** [comment]
Haha, fair!

**Comment by ActuallyACat** [comment]
Avatar, Badge, Button, Card, Collapsible, Divider, Dropdown, and Empty State were covered in this PR https://github.com/cultureamp/kaizen-design-system/pull/1754
