### ISSUE TITLE
Box should be RTL self aware

### ISSUE THREAD

**Issue by dougmacknz** [cultureamp/kaizen-design-system#1762]
Paddings and margins can use the new logical properties
![image](https://user-images.githubusercontent.com/1811583/125588965-8579e220-77c8-4274-be1c-f16a2fb0e9b1.png)

The RTL prop can be deprecated, or possibly just removed straight away depending on how many usages are actually using the RTL prop.

**Comment by ActuallyACat** [comment]
I don't think we can make this a blanket rule - there's going to be situations where we'd want some right/left properties to be logical properties, and other times you'd want the padding to be there regardless of language direction. 

I'd hazard a guess that the RTL prop is seldomly used though. It would be good to explore what people need.

**Comment by dougmacknz** [comment]
> I'd hazard a guess that the RTL prop is seldomly used though

Yep, and our RTL support will be suffering as a result. It's quite a hassle to get the text direction from inside React so that it can be passed into this component every time you want to use it.

> other times you'd want the padding to be there regardless of language direction

This should be rare, and definitely the one to have more friction on it if we wanted to support both.

**Comment by dougmacknz** [comment]
After bringing this to the Kaizen advocate meeting today, there was a pretty unanimous decision that consumers wouldn't want this to just magically happen (my bad 😅). I do believe the current way is still problematic though, and I'm pretty sure people aren't using it, so I will create a new issue that's more of a discussion around how we might make supporting RTL with Box easier for consumers.
