### ISSUE TITLE
Cannot override text styling in InlineNotification component

### ISSUE THREAD

**Issue by Hannah-de** [cultureamp/kaizen-design-system#1843]
We would like to create an inline notification that looks like this

![image](https://user-images.githubusercontent.com/19618930/129317266-2b1d592a-e893-4eb0-b4ca-25e1b0bb84ac.png)

Currently we can only achieve this
![image](https://user-images.githubusercontent.com/19618930/129317244-75041ce2-ae5b-4358-82d0-8b7cd25c8421.png)

```     
 <InlineNotification
                type="negative"
                title={formatMessage(
                  strings.adminEc.translationsStep.errorTitle
                )}
                automationId="notification1"
              >
                  {formatMessage(strings.adminEc.translationsStep.errorText)}
                  {error ? errorList(error) : null}
 </InlineNotification>
```

Some initial investigation shows that we can't override the built in flexbox - was suggested a prop is added that can be used to force the multiline wrap when needed https://cultureamp.slack.com/archives/C0189KBPM4Y/p1628834981112000

**Comment by lloydstubber** [comment]
@Hannah-de this has now been merged and you can achieve what you're after with the `forceMultiline` prop :)
