### ISSUE TITLE
Input: improvements

### ISSUE THREAD

**Issue by reetaa** [cultureamp/kaizen-design-system#1845]
The Kaizen `Input` accepts some icons. My question is - how flexible an Input  has to be?

Maybe flexibility is desired? The consumer can pass in any icon they like. However, for a consumer it's a nuisance to find the correct icons each time it's used. So, would it be a considerable suggestion to:
* Have predefined icons in `Input` based on the states we define in design system?

#### Current behaviour

```
<Input startIconAdornment={isRange ? <Icon icon={dateRangeIcon} /> : <Icon icon={dateIcon} />} 
   endIconAdornment={onError && <Icon icon={exclamationIcon} />}
 />
```
#### Possible future behaviour
 ```
    <Input prefix={prefix} suffix={suffix} />
```

**Comment by ActuallyACat** [comment]
This is still relevant - reopening
