### ISSUE TITLE
guidance and/or code for unordered and ordered lists

### ISSUE THREAD

**Issue by mbylstra** [cultureamp/kaizen-design-system#1847]
There is currently nothing in Heart or in the code around ordered and unordered lists `ol`'s and `ul`'s, so when the `<ul>`  or `<ol>` tags are used the app just picks up whatever was defined globally (either the browser defaults, reset css or normalise). The results are rarely ideal.

There also aren't any designs in the Figma file, so it's not clear whether there should be margins or how the bullets should be positioned.

**Comment by lloydstubber** [comment]
Moved into a discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1867)
