### ISSUE TITLE
AllowedColors prop in Heading and Paragraph components is too limited

### ISSUE THREAD

**Issue by mbylstra** [cultureamp/kaizen-design-system#1858]
As of the time of writing, here are some examples the Figma file that are not currently supported: 

- it's permissible to use blue-500, green-600 and red-600 on white and light grey backgrounds (and I've need to do this in product recently - I just worked around it by not having the text colored, which was a bummer): https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit%3A-Heart?node-id=1929%3A784
- the ProgressBar uses a Heading4 style with an opacity of 0.8 (the allowed reduced-opacity option is 0.7) (https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit%3A-Heart?node-id=1929%3A20890)

Just some quick thoughts:
- is the best solution is to keep adding more options or make it more flexible? (it could at least be limited to available tokens, rather than any rgb value). I'm not sure - there's pros and cons.
- the cluny-500 text is a tricky one because it's only allowed if the background is white, and i don't know how the paragraph component

**Comment by lloydstubber** [comment]
Moved into discussions
