### ISSUE TITLE
There's no Heading or Paragraph component in our docs

### ISSUE THREAD

**Issue by lloydstubber** [cultureamp/kaizen-design-system#1865]
Going through the issues and tagging all the things™️ with the correct labels but it seems we don't have `<Heading />` or `<Paragraph />` outside of the Typography page under guidelines, therefor, no section to link issues to.

Would be great to create these component pages or just a Typography page under components? Unsure.

**Comment by dougmacknz** [comment]
These do exist now, though we've also got [an open issue saying that they shouldn't exist](https://github.com/cultureamp/kaizen-design-system/issues/2363) 😅
