### ISSUE TITLE
Avatar component doesn't display correctly with languages other than English

### ISSUE THREAD

**Issue by Hannah-de** [cultureamp/kaizen-design-system#1905]
### If it's a discussion, please start one [here](https://github.com/cultureamp/kaizen-design-system/discussions).

- [X] Before opening this issue, I've searched open and closed issues for a fix.

## Expected Behavior

Have started a discussion to resolve expected behaviour [here ](https://github.com/cultureamp/kaizen-design-system/discussions/1907)

## Actual Behavior (please provide screenshots if it's a visual issue)

When a users name is in a language other than english, the avatar displays the characters as symbols

_(screenshots removed by @jasononeil)_

## Steps to Reproduce the Problem

1. User is in a company where employees have their `personal details` -> `demographic` -> `name` field in a language other than english
2. User navigates to company directory
3. User sees the employees avatars with symbols instead of their name initials

## Specifications (please add any other notable libs/details)

- Kaizen version:

## Labelling

1. If related to a component, please add a label like so `component:mycomponent`.
2. Then label with `bug`, `enhancement`/`feature`\* or `documentation`.

**\* A feature is a new component or piece of functionality and an enhancement is an improvement to an existing component or piece of functionality.**

**Comment by jasononeil** [comment]
Hi @Hannah-de, it looks like this behaviour:

> When a users name is in a language other than english, the avatar displays the characters as symbols

is coming from somewhere else in your product, as the Kaizen component does support all unicode characters. I've added a storybook story to show this (see the PR I linked to).

The discussion about the intended behaviour is a good one though - thank you for starting it :) Depending on the outcome of that discussion, we can open another issue to talk about updating the component if we decide it needs to change behaviour.
