### ISSUE TITLE
Text Area form field does not show description by default

### ISSUE THREAD

**Issue by talbet** [cultureamp/kaizen-design-system#1929]
## Expected Behavior

Adding the `description` prop to the `<TextAreaField>` component should render the description provided

## Actual Behavior (please provide screenshots if it's a visual issue)

If I add a `description` prop to the `<TextAreaField>` component, it doesn't render until I add a variant prop. I think that either: the `variant` prop should not be marked optional, or we should set `variant` to `default` when it is not provided.

## Steps to Reproduce the Problem

1. render `TextAreaField
      id="reply"
      labelText="Your reply"
      description="Your reply will only be seen by you"
    />`
2. the description does not appear

## Specifications (please add any other notable libs/details)

- Kaizen version: "@kaizen/draft-form": "^3.4.10",

**Comment by dougmacknz** [comment]
All fixed, thanks for logging this one @talbet
