### ISSUE TITLE
Select component - Current selection is highlighted in dropdown and chevron direction doesn't change

### ISSUE THREAD

**Issue by Hannah-de** [cultureamp/kaizen-design-system#1982]
### If it's a discussion, please start one [here](https://github.com/cultureamp/kaizen-design-system/discussions).

- [x] Before opening this issue, I've searched open and closed issues for a fix.

## Expected Behavior

- The currently selected option is in bold font
- The option being hovered over or clicked on is highlighted
- The chevron points up when the menu is open

![image](https://user-images.githubusercontent.com/19618930/135779828-dc20dbce-910b-4763-b400-31893edcb2ce.png)

## Actual Behavior (please provide screenshots if it's a visual issue)

- The current selection is highlighted by default
- The chevron points in one direction, regardless of if the dropdown is open / closed

![image](https://user-images.githubusercontent.com/19618930/135779807-90f45034-819b-4aa4-bfe4-25ff616223a4.png)

## Steps to Reproduce the Problem

1. Open select component
2.
3.

## Specifications (please add any other notable libs/details)

- Kaizen version:

## Labelling

1. If related to a component, please add a label like so `component:mycomponent`.
2. Then label with `bug`, `enhancement`/`feature`\* or `documentation`.

**\* A feature is a new component or piece of functionality and an enhancement is an improvement to an existing component or piece of functionality.**

## No Sensitive Information
As this is a public repo, please do not include screenshots that may share sensitive information about our customers.

**Comment by pandurijal** [comment]
is someone already working on this or can I try to fix this issue?

**Comment by Hannah-de** [comment]
@pandurijal not that I know of, I think you can try fix it :-)

**Comment by christian314159** [comment]
The issue with the Chevron has been fixed; we're tracking the select/focus state issue in Jira now.
