### ISSUE TITLE
ToggleSwitchField ON storybook demo looks off

### ISSUE THREAD

**Issue by okeeffed** [cultureamp/kaizen-design-system#204]
**Issue**

Image attached. Looks like the ON state doesn't sit with a similar distance to the edge that the OFF state does.

**Reference**

<img width="153" alt="Screen Shot 2020-01-07 at 8 00 52 am" src="https://user-images.githubusercontent.com/4946487/71848571-ec855980-3123-11ea-9b3d-272a1a7b6eeb.png">

**Comment by didoesdigital** [comment]
The alignment of the Toggle Switch in the storybook demo was fixed in https://github.com/cultureamp/kaizen-design-system/pull/228: [Toggle Switch story](https://cultureamp.design/storybook-static/?path=/story/toggleswitchfield-react--on-kaizen-site-demo)
