### ISSUE TITLE
Popover: visible prop does nothing

### ISSUE THREAD

**Issue by OliBridgman** [cultureamp/kaizen-design-system#2109]
### If it's a discussion, please start one [here](https://github.com/cultureamp/kaizen-design-system/discussions).

- [x] Before opening this issue, I've searched open and closed issues for a fix.

## Expected Behaviour
Popover should be visible or not visible based on the prop `visible`

## Actual Behaviour (please provide screenshots if it's a visual issue)

Visible is ignored completely.

```
export type PopoverProps = {
  readonly automationId?: string
  readonly visible?: boolean
  ...theRest
}

export const Popover: PopoverModernType = ({
  automationId,
  children,
  variant = "default",
  placement = "bottom",
  size = "small",
  heading,
  dismissible = false,
  onClose,
  singleLine = false,
  customIcon,
  referenceElement,
}: PopoverProps) => {
```
  
https://github.com/cultureamp/kaizen-design-system/blob/master/draft-packages/popover/KaizenDraft/Popover/Popover.tsx#L61

## Steps to Reproduce the Problem

1. Render a Popover
2. Pass visible={false}
3. See Popover

## Specifications (please add any other notable libs/details)

- Kaizen version:

## Labelling

1. If related to a component, please add a label like so `component:mycomponent`.
2. Then label with `bug`, `enhancement`/`feature`\* or `documentation`.

**\* A feature is a new component or piece of functionality and an enhancement is an improvement to an existing component or piece of functionality.**

## No Sensitive Information
As this is a public repo, please do not include screenshots that may share sensitive information about our customers.

**Comment by ActuallyACat** [comment]
Closed in https://github.com/cultureamp/kaizen-design-system/pull/2121#pullrequestreview-788683184

**Comment by OliBridgman** [comment]
Soz I thought they would auto close!
