### ISSUE TITLE
Master builds are sometimes failing despite branch builds passing

### ISSUE THREAD

**Issue by jasononeil** [cultureamp/kaizen-design-system#2267]
Example failed build: https://buildkite.com/culture-amp/kaizen-design-system/builds/23996#158c469c-6f81-4e77-a817-0c2f2c607951/398-534
Example fix in that instance: #2209 

To fix:

- [ ] Add a dry-run of the "publish" step to our branch builds

**Comment by zioroboco** [comment]
Unfortunately, lerna doesn't have a dry-run flag.

This looks like a config mismatch between the type checks and build scripts.
