### ISSUE TITLE
Likert scales need borders for colour contrast requirements

### ISSUE THREAD

**Issue by dougmacknz** [cultureamp/kaizen-design-system#2289]
As part of the accessibility audit, we updated our Capture likert scales to have 2px borders like this:
![image](https://user-images.githubusercontent.com/1811583/141728812-faa198e3-4a27-4014-9889-a2eca65335df.png)

Capture isn't using the Kaizen LikertScale component yet, so this change was only made there. We should make the same change to the Kaizen version.

**Comment by lisatassone** [comment]
@ActuallyACat Lemme know when you want to pair on this since you were out sick on the designated day.

**Comment by dougmacknz** [comment]
Done in https://github.com/cultureamp/kaizen-design-system/pull/2670
