### ISSUE TITLE
Remove circular dependencies that exist between button and component library

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#2371]
### If it's a discussion, please start one [here](https://github.com/cultureamp/kaizen-design-system/discussions).

- [ ] Before opening this issue, I've searched open and closed issues for a fix.

## Expected Behavior
We should not have any circular dependencies between any packages within Kaizen.

## Actual Behavior (please provide screenshots if it's a visual issue)
Button depends on component-library depends on button
https://github.com/cultureamp/kaizen-design-system/blob/master/draft-packages/button/package.json#L35
https://github.com/cultureamp/kaizen-design-system/blob/master/packages/component-library/package.json#L36

This is a little tricky to resolve as both packages rely on each other heavily. It's likely going to be easier to stop component-library depending on button, over button depending on component library as the button package needs component-library for icons 😭 

## Specifications (please add any other notable libs/details)

- Kaizen version:

## Labelling

1. If related to a component, please add a label like so `component:mycomponent`.
2. Then label with `bug`, `enhancement`/`feature`\* or `documentation`.

**\* A feature is a new component or piece of functionality and an enhancement is an improvement to an existing component or piece of functionality.**

## No Sensitive Information
As this is a public repo, please do not include screenshots that may share sensitive information about our customers.

**Comment by christian314159** [comment]
@dougmacknz This has been resolved, hasn't it?

**Comment by dougmacknz** [comment]
Yup! Fixed by https://github.com/cultureamp/kaizen-design-system/pull/2383
