### ISSUE TITLE
How do we pick time? Guidance needed.

### ISSUE THREAD

**Issue by Confidenceman02** [cultureamp/kaizen-design-system#261]
## Conversations
https://cultureamp.slack.com/archives/CETLTFG9G/p1580774357058400

## What does a time picker do?
Its a way for a user to pick a time value e.g. 08:30am.

## What do we have so far?
Launch plan uses a Select component with incremented time values.
<img width="267" alt="Screen Shot 2020-02-04 at 4 59 26 pm" src="https://user-images.githubusercontent.com/25443812/73719586-d349ea00-476f-11ea-9561-64467fb03501.png">

**Comment by jeremy8883** [comment]
Another point to think about, is if we should show 12 or 24 hour time. It would be nice if we could dynamically adapt, depending on the user’s locale.
