### ISSUE TITLE
Table: header cells do not align with body cells

### ISSUE THREAD

**Issue by mbylstra** [cultureamp/kaizen-design-system#2943]
### If it's a discussion, please start one [here](https://github.com/cultureamp/kaizen-design-system/discussions).

- [ ] Before opening this issue, I've searched open and closed issues for a fix.

## Expected Behavior

header and body cells should be aligned

## Actual Behavior (please provide screenshots if it's a visual issue)

![image](https://user-images.githubusercontent.com/702885/188071609-0d6af0f1-b96f-4a73-997e-df18deaecfa6.png)
```
      <TableContainer>
        <TableHeader>
          <TableHeaderRow>
            <TableHeaderRowCell
              labelText="xxxx"
              width={8 / 12}
              align={"start"}
            />
            <TableHeaderRowCell
              labelText="xxxx"
              width={2 / 12}
              align={"start"}
            />
            <TableHeaderRowCell
              labelText="xxxx"
              width={2 / 12}
              align={"start"}
            />
          </TableHeaderRow>
        </TableHeader>
        <TableCard>
          <TableRow>
            <TableRowCell width={8 / 12}>
              <Paragraph tag="div" variant="body">
                xxxx
              </Paragraph>
            </TableRowCell>
            <TableRowCell width={2 / 12}>
              <Paragraph tag="div" variant="body">
                xxxx
              </Paragraph>
            </TableRowCell>
            <TableRowCell width={2 / 12}>
              <Paragraph tag="div" variant="body">
                xxxx
              </Paragraph>
            </TableRowCell>
          </TableRow>
        </TableCard>
      </TableContainer>
```

## Steps to Reproduce the Problem

1. Go to https://cultureamp.design/storybook/?path=/docs/components-table--multiline, you should see that the table headers are not aligned in all of the sotires. I have tried in Firefox and Chrome and it seems broken in both.

## Specifications (please add any other notable libs/details)

- Kaizen version: "@kaizen/draft-table": "^5.2.2"

## Labelling

1. If related to a component, please add a label like so `component:mycomponent`.
2. Then label with `bug`, `enhancement`/`feature`\* or `documentation`.

**\* A feature is a new component or piece of functionality and an enhancement is an improvement to an existing component or piece of functionality.**

## No Sensitive Information
As this is a public repo, please do not include screenshots that may share sensitive information about our customers.

**Comment by gyfchong** [comment]
Thanks for catching this @mbylstra, unfortunately this falls low on our priorities. However you are welcome to contribute the fix to this. Thanks!
