### ISSUE TITLE
Elm Upgrade Shims is being used when it isn't necessary

### ISSUE THREAD

**Issue by jasononeil** [cultureamp/kaizen-design-system#349]
Culture Amp undertook a long term project to upgrade from Elm 0.18 to Elm 0.19, and we had a package called "elm-upgrade-shims" that made it possible for common code, like our Kaizen components, to work on both Elm 0.18 and Elm 0.19 despite the breaking API changes between Elm versions.

Now that all Culture Amp code has been upgraded, we should get rid of the shims from this repository and simplify the code to just use standard Elm 0.19 APIs.

**Comment by mbylstra** [comment]
I will also point out that this is a constant source of pain for new Elm projects as we don't have a proper Elm dependency installer for Elm. You just get a confusing Elm error which doesn't tell which package you actually need to install.

**Comment by mbylstra** [comment]
I'm tackling this for our team's new tech debt removal baby steps mission 🎉

**Comment by mbylstra** [comment]
This is being chipped away at in this PR: https://github.com/cultureamp/kaizen-design-system/pull/577

**Comment by ActuallyACat** [comment]
Looks like this has been completed 🎉 Closing the issue.
