### ISSUE TITLE
Border token structure is not scalable

### ISSUE THREAD

**Issue by sebpearce** [cultureamp/kaizen-design-system#373]
Currently our border widths are 2px, but if we ever want to add more, we'll need to come up with names that do not fall on a continuum – for example, we currently have a `solid` style that is 2px, but if we were to introduce a 3px style, we'd have to call it something like `solidThick`.

A more scalable solution would be to use a sizing spectrum like this:

```
kz-border-width-xxs: 0.5px  / kz-border-width-xxs: 1pt for any possible hairline needs
kz-border-width-xs: 1px
kz-border-width-sm: 2px
kz-border-width-md: 3px 
kz-border-width-lg: 4px
kz-border-width-xl: 5px
kz-border-width-xxl: 6px
```

Of course, this also restricts us at a certain point, but we might be OK with that trade-off.

It arguably wouldn't make much sense to use a system like this now while we only have one size (2px), since it would exist by itself as `kz-border-width-sm` and that name implies the existence of other sizes, which is confusing. If we wanted to update our current name in the future, we could use a codemod or similar.

**Comment by lloydstubber** [comment]
Moved into discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1879)
