### ISSUE TITLE
There's no Progress bar guidance

### ISSUE THREAD

**Issue by didoesdigital** [cultureamp/kaizen-design-system#379]
We need to provide Progress bar guidance for designers and engineers so they can rapidly make consistent decisions and build features that align with our design vision.

It's worth noting that we need progress bars for both "loading" progress and "workflow" progress. Here are some examples:

![image](https://user-images.githubusercontent.com/2476974/78752109-d3a47280-79b6-11ea-8a6b-e635a6120858.png)

![image](https://user-images.githubusercontent.com/2476974/78752101-ce472800-79b6-11ea-84c6-567202d4977c.png)

![image](https://user-images.githubusercontent.com/2476974/78752128-dc954400-79b6-11ea-8ab8-78f4ff751de0.png)

![image](https://user-images.githubusercontent.com/2476974/78752133-e028cb00-79b6-11ea-8c78-381954173418.png)

![image](https://user-images.githubusercontent.com/2476974/78752141-e454e880-79b6-11ea-9091-085cf1e43e74.png)

**Comment by didoesdigital** [comment]
Useful link: https://ant.design/components/progress/#header

**Comment by vicchirino** [comment]
Here is some progress bar that we use in performance in the goal page. Added this just in case is helpful 
![image](https://user-images.githubusercontent.com/3228237/79593347-b015b200-80b1-11ea-84d8-2175071be604.png)
