### ISSUE TITLE
There's no guidance block documentation

### ISSUE THREAD

**Issue by didoesdigital** [cultureamp/kaizen-design-system#388]
We have a guidance block draft component thanks to https://github.com/cultureamp/kaizen-design-system/pull/280 but no guidance on how/when to use it.

![image](https://user-images.githubusercontent.com/2476974/79412507-079c1b00-7fe9-11ea-81f9-767182633d83.png)

![image](https://user-images.githubusercontent.com/2476974/79412521-0c60cf00-7fe9-11ea-86e1-72b11880152b.png)

![image](https://user-images.githubusercontent.com/2476974/79412541-1551a080-7fe9-11ea-9004-291f555707e9.png)

![image](https://user-images.githubusercontent.com/2476974/79412544-17b3fa80-7fe9-11ea-9f94-37a0bbd6fcd5.png)

![image](https://user-images.githubusercontent.com/2476974/79412547-1a165480-7fe9-11ea-96d9-3294059b8475.png)

**Comment by didoesdigital** [comment]
![image](https://user-images.githubusercontent.com/2476974/79412855-c6583b00-7fe9-11ea-9d13-1f10bdcedfb8.png)

**Comment by dlimiter** [comment]
Some examples from Trello:
<img width="525" alt="trello1@2x" src="https://user-images.githubusercontent.com/152166/80167914-f3799e80-8624-11ea-955d-6a1b15bc1bf7.png">
<img width="435" alt="trello2@2x" src="https://user-images.githubusercontent.com/152166/80167920-f83e5280-8624-11ea-8c33-076ad7f8f98d.png">
<img width="437" alt="trello3@2x" src="https://user-images.githubusercontent.com/152166/80167926-fb394300-8624-11ea-8fea-5d9f2dd2aa47.png">
