### ISSUE TITLE
Common rules like font antialiasing are not centralised

### ISSUE THREAD

**Issue by sebpearce** [cultureamp/kaizen-design-system#516]
The following code is duplicated across several components:
```
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
```

This should be centralised – possibly in the front-end-ops repo as part of the CSS reset.

**Comment by ActuallyACat** [comment]
IF deciding not to take a stance on aliasing in Kaizen we should warn against overrides in consumers with Stylelint.

**Comment by ActuallyACat** [comment]
* We should not centralise this 
* Should this also be a stylelint rule?
* Will designers have an issue with this rule being removed?

**Comment by mbylstra** [comment]
Is this issue specifically about font smoothing or is it about the idea of having centralised global styles in general? If it's about generally having centralised global styles in general, then these issues are somewhat related:
- https://github.com/cultureamp/kaizen-design-system/issues/1847 (_if_ we decided global styles was the way to go for `ul`s and `ol`'s)
- https://github.com/cultureamp/kaizen-design-system/issues/1723 (_if_ we decided global styles was the way to go for `a`'s)

**Comment by lloydstubber** [comment]
Moved into discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1878)
