### ISSUE TITLE
Inactive hover state for checkboxes display the checked icon

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#546]
## Issue
When the checkbox is not selected and is in either a focus or hover state, the checked icon is still visible (checkbox is white on wisteria-100 background - so it's hard to see). 
![checkbox](https://user-images.githubusercontent.com/1621182/84735842-cd9ac580-afe7-11ea-9768-ca921079074d.gif)

**Intended behaviour**
The intended behaviour is for the checked icon not to be visible: 
https://www.figma.com/file/GMxm8rvDCbj0Xw3TQWBZ8b/Zen-UI-Kit?node-id=1929%3A20451

Thanks @Confidenceman02 for reporting!

**Comment by didoesdigital** [comment]
@ActuallyACat I think this was fixed recently, can you confirm? And close?

**Comment by ActuallyACat** [comment]
Issue resolved - closing.
