### ISSUE TITLE
We have no component for "toggle buttons" (naming is an issue here)

### ISSUE THREAD

**Issue by didoesdigital** [cultureamp/kaizen-design-system#551]
## Problem

We need clarity on "toggle buttons" and we need components that support toggle behaviour

## Background

"Toggle Buttons" have on/off states and used for things like: 

- "favoriting" an item (often a star icon button)
- bookmarking (often a bookmark icon)
- "liking" (often a heart icon)
- WYSIWYG editor buttons (such as bold, italics, underline, left alignment, center alignment, right alignment…)

We use them for saving comments and choosing a focus area.

Naming is hard. These behave slightly differently from our existing toggle switches and existing icon buttons. Some design systems call them Button Groups when they're used for a set such as left/center/right alignment. We use [Button Group](https://cultureamp.design/components/button-group/) to describe buttons connected by a line that perform related actions (which may or may not be toggle buttons).

## Extra info

- Toggle buttons https://material.io/design/components/buttons.html#usage
- Button group with segmented buttons: https://polaris.shopify.com/components/actions/button-group
- Button icons: https://www.lightningdesignsystem.com/components/button-icons/
- ARIA switch role: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Switch_role

**Comment by kemblesong** [comment]
Functionally similar to a checkbox, but is modeled as "on" and "off" states, rather than "checked" and "unchecked", according to this: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Switch_role

Interestingly, our CheckboxField component takes "on" and "off" as values for the checked status property https://github.com/cultureamp/kaizen-design-system/blob/master/draft-packages/form/KaizenDraft/Form/Primitives/Checkbox/Checkbox.tsx#L11

Whether this is desirable for consistent prop values across both, or not desirable because of incorrect semantics is up for debate.

I was also thinking this should be called "Switch" button instead of "Toggle" button, if we're talking specifically about "a button with the switch role"

**Comment by mindycultureamp** [comment]
Agree that it has an on/off state, which aligns with a toggle or a checkbox.

The name "toggle buttons" makes sense to me. I  have seen "toggle" and "switch" used interchangeably or together in this case (e.g. https://www.nngroup.com/articles/toggle-switch-guidelines/)  

Is there a difference between "toggle" and "switch"?

**Comment by didoesdigital** [comment]
I wonder if we ought to add something like a switch=on|off prop to each of the relevant components: button, icon button, checkbox, toggle switch, button group…

**Comment by sentience** [comment]
Everything I know on this subject I learned from https://inclusive-components.design/toggle-button/

In brief, it recommends using a `<button aria-pressed="true|false">`, which is read by screen readers as a “toggle button” or “push button”.

**Comment by ActuallyACat** [comment]
> I wonder if we ought to add something like a switch=on|off prop to each of the relevant components: button, icon button, checkbox, toggle switch, button group…

`switch=on|off` makes sense to me. Like Kemble mentioned it aligns to aria switch and those values are already used in checkboxes. Would we want the Toggle Buttons to support all the variants that the current buttons? Or a subset of the variants? 

toggle, switch, and toggle switch all feel interchangeable to me 🤷‍♀️

**Comment by lloydstubber** [comment]
Instead of moving this over to discussions, this is quite old so I'm going to close this. Feel free to open back up and I can port it over.
