### ISSUE TITLE
Icons should be split out of the component library

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#562]
A lot of our draft-packages depend on `@kaizen/component-library` purely for icons. See these for examples:

https://github.com/search?q=require%28%22%40kaizen%2Fcomponent-library%2Ficons+repo%3Acultureamp%2Fkaizen-design-system+path%3A%2Fdraft-packages&type=Code&ref=advsearch&l=&l=

This is a problem as consuming repos bring in lots of versions of the component-library, which is a large dependency. At times these are not possible to resolve to one version.

**Comment by lloydstubber** [comment]
Moved into discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1877)
