### ISSUE TITLE
There's no Filter drawer component

### ISSUE THREAD

**Issue by didoesdigital** [cultureamp/kaizen-design-system#584]
## Design

Work in progress shot:

![image](https://user-images.githubusercontent.com/2476974/85813028-8231a580-b7a5-11ea-9a00-d68268a7a1de.png)

## Needs

Needs to align to [Filtering guidelines](https://cultureamp.design/guidelines/filtering/).

### Filter button

- Unlike our usual secondary buttons that don't have a background in default state (it's on hover), the Filter button has background fill in default state
- RTL icon may need to swap with filter button text.

### Filter button badge

- Badges start "Active" style (informative Cluny) and if evidence from user tests with customers shows that they're missing that valuable context, we can increase its prominence to a negative Coral style.
- RTL badge may need to swap with filter button icon + text.

### Filter metadata

- There is space needed next to the filter button for metadata, which occupies 1 row without wrapping (but we'll likely support that for edge cases), e.g. "Participation 1%, Responses 1 of 170", which is updated by filter but always shown, even when no filters selected

### Filter drawer

- The drawer will grow to support increasing numbers of applied filters in both directions.
- The component itself may be responsible only for sending a close filter drawer event and letting the consumer know when it's closed.
- Regarding UX, we may need an explicit close button for accessibility (see modal behaviour and WCAG recommendations) but need to balance that with avoiding nested close icons where a specific filter field may have its own closing icon. In practice, it may be a "Cancel" button (that discards latest changes to filters) and an "Apply" button (that applies recent changes) that both "Close" the drawer. Note, this is separate from ["clearing" all filters](https://cultureamp.design/guidelines/filtering/#clear-filters)
- Internal scrolling section within the drawer button, in case someone applies 50 filters and for small screens. (See modal behaviour.)
- You can click outside the drawer to close it (similar to modal background) and you can hit escape to close it.
- RTL drawer may need to align to the opposite edge of the filter button.
- We may need to support both [live and batch filtering](https://cultureamp.design/guidelines/filtering/#choosing-between-live-or-batch-filters).

## Delivery

- We need a React component first. We can follow with Elm or Web Components in the future.
- First iteration may have overflow on y-axis for scrolling in the main body with some padding, without a dedicated "footer" area for Cancel/Apply buttons.
- In the future, we may explore the filter dropdown container having a 100% width all the time.

**Comment by didoesdigital** [comment]
Is "filter button" a new type of Button that should be a prop on the Button component?

**Comment by sebpearce** [comment]
To me it looks as though Button should be modified to allow an optional "badge" (or whatever the 2 in the blue circle is called). If we do that, then this component could be a level up from Button, where it:
- imports Button for the buttony part
- adds the meta data text
- imports Menu for the dropdown part (doesn't need to use menu items)
- (TBD) could do logic stuff as well if the consumer doesn't do that bit

**Comment by didoesdigital** [comment]
Added in https://github.com/cultureamp/kaizen-design-system/pull/590
