### ISSUE TITLE
Button does not allow combination of destructive/secondary

### ISSUE THREAD

**Issue by makenosound** [cultureamp/kaizen-design-system#650]
<img width="977" alt="image" src="https://user-images.githubusercontent.com/4353/87386234-5c006800-c5e3-11ea-9385-2061292ce192.png">

The design guidelines reference a *Secondary / Destructive* button but when I use those in combination I get only the standard _Destructive_ styles.

**Comment by dougmacknz** [comment]
@sebpearce added support for this earlier this year: https://github.com/cultureamp/kaizen-design-system/pull/1109 😎
