### ISSUE TITLE
Calling `preventDefault` for `<Button onClick={...` should be user-controllable

### ISSUE THREAD

**Issue by makenosound** [cultureamp/kaizen-design-system#657]
👋 Have an issue using a standard `<Button>`. We’re using it as a link thusly:

```jsx
<Button
  label="Preview message"
  href={previewUrl}
  newTabAndIUnderstandTheAccessibilityImplications
/>
```

This opens a preview URL in a new tab. I’d like to be able to add an event to our analytics to track this, but the current API for `<Button>` makes that awkward. If I do this:

```jsx
<Button
  label="Preview message"
  href={previewUrl}
  newTabAndIUnderstandTheAccessibilityImplications
  onClick={() => logEvent(...) }
/>
```

Then `<Button>` will call `event.preventDefault` on the click event, and so I get my log but not the behaviour I want for a user. It would be nice to have some way to opt _out_ of this behaviour easily so that we don’t have to implement awkwardness like this to get the behaviour we need in these sort of situations:

```jsx
<span
  onClick={() => {
    logEvent(...)
  }}
>
  <Button
    label="Preview message"
    href={previewUrl}
    newTabAndIUnderstandTheAccessibilityImplications
  />
</span>
```

We _could_ implement an additional prop like `preventDefaultOnClick` but my _feeling_ is that’s a bandaid to the existing behaviour rather than the right way to approach this. I think the _right_ behaviour here would be to make the event available to `onClick` so that the consumer can control that behaviour themselves:

```diff
  onClick={(e: any) => {
    if (onClick) {
-     e.preventDefault()
      onClick && onClick(e)
    }
  }}
```

That would be a breaking change I think, but going down the other path means we’d need to add this overrides for any other sort of behaviour we’d like `stopImmediatePropagation` or `onMouseDown` etc.

**Comment by dougmacknz** [comment]
This was fixed as part of https://github.com/cultureamp/kaizen-design-system/pull/763. Buttons will no longer `preventDefault` for you 🎉
