### ISSUE TITLE
Working with `Table` column widths

### ISSUE THREAD

**Issue by jeremy8883** [cultureamp/kaizen-design-system#668]
Following from our slack conversation:

> Question about the Table component. One of the problems that we’ve encountered often, is that the table uses display: flex, and either percentages or fixed pixel values to choose the widths of each column. The problem is that as soon as the text content changes, or the language changes to german, the cell widths become inconsistent.
> I understand why it was done this way, because it adds more flexibility for the expandable table row animations. However, 90% of the time, we don’t need this in perform.
> I was wondering as a solution, if kaizen could supply an alternative component, which explicitly uses `display: table`. That way, if there are any minor issues in our column sizing, the browser will make the appropriate adjustments.
> Or if there are any other ideas? I’m also good to create a PR. 

To sum up the responses so far from @mbylstra and @ActuallyACat :

* We could name the components `Table` and `ExpandableTable`. Or just have a single table with a prop that proxies to the appropriate component type.
* Using css grid would be nice, but we need to support ie11
* It has been attempted to do in `display: table`, and it worked, but the css complexity was high. The new zen designs are more simple, so maybe we could try and have the new zen components use `display: table`, with the expandable rows included.
* This is a hard problem, and we look at all of our current use cases to make an informed decision.

**Comment by jeremy8883** [comment]
I've gone through perform, and listed all of the requirements that I can find. See the jira ticket PMC-428 for supporting screen shots.

### Currently supported (and will still be required)
* Row to be clickable, using `a`nchor or `button` elements, with `onClick` support. Note that every cell is clickable, except for the last split button column. This is because:
  1. nesting buttons is illegal
  2. it gives a little bit of click room around the split button, so if the user misses the click, they don't get taken to a completely different page.
* Some tables have table headers, some do not
* Mix between fixed column widths and dynamic widths
* Sortable column headers
* Checkbox fields, with "check all" in the table heading
* Expandable rows. An api call also needs to also be made upon expand.

### Not explicitly supplied by `Table`, but needs to compatible
* We have icon buttons to the right in a lot of tables. In the legacy non-kaizen tables, they show tooltips on hover. Shall we do the same here?
* Allow for "more" and "splitbutton" menus. Not that the table should support this explicitly of course, but I mention this because there was a previous issue where `overflow: hidden` was used, and was clipping off the dropdown menu. This is now fixed, but just to be aware.
* Infinite scroll

### Feature requests
* Requirement for `display: table`, since we have encountered issues with smaller breakpoints, and cell width inconsistencies with different languages.
* Responsive breakpoints for column widths - right now these are coming in through javascript values. I'm alright with this, but there are couple of issues to raise.
  1. our current preference is to use scss for styling, and only resort to js styling when needed. Not a big deal of course, the code just gets a bit tedious and messy.
  2. It's not server-side render friendly. I'm not sure if this is a current requirement or not, but it's good to account for in the future.
Could we allow for passing `className` just for the table cells, or is that giving too much control?
* I see that the `a`nchor rows are sometimes indicated with a right chevron. Should we support this in kaizen, or simply leave it to the consumer to add? Note that some tables have a mix between `a`nchor rows, and no anchor rows.
* There are some planned designs to have tabs baked inside the table. If this is infeasible, I can ask design if there are any alternatives. See the jira ticket for a snapshot.
* Cell padding adjustments. Both at a cell level, and/or at a global table level for certain breakpoints.
* Mobile support - So what we've been doing currently is either removing columns, or flipping the row display into a column. Which works fine, although I think it would be good to show some mobile examples in storybook, so we know to follow a consistent pattern.
* `colspan` support - I don't see any existing use cases currently, but I figure we may as well support it.
* custom `aria-` and `data-` props to be passed down

**Comment by lloydstubber** [comment]
Moved into discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1876)
