### ISSUE TITLE
There's no component for visually hidden content

### ISSUE THREAD

**Issue by didoesdigital** [cultureamp/kaizen-design-system#743]
We have no component for "visually hidden" content. This means that A) there's no visibility of existing solutions, and B) engineers have to handle visually hidden content manually every single time.

Several people have reported having no idea what `.sr-only` (screen reader only) means. It would be clearer to use "visually hidden".

Examples in other design systems:

- https://react-spectrum.adobe.com/react-aria/VisuallyHidden.html
- https://seek-oss.github.io/braid-design-system/components/HiddenVisually/

## Current

We have one mixin in `packages/component-library/styles/mixins/_forms.scss`:

```
// Visually hide a native input but not prevent it from being keyboard focusable
// Useful in situations such as applying custom styling to checkboxes
@mixin form-input-visually-hidden() {
  opacity: 0;
  position: absolute;
  :global(.ideal-sans) & {
    // This is to override bootstrap styles. Remove when appropriate
    position: absolute;
  }
}
```

We also have `packages/component-library/styles/utils.scss`:

```
// Only display content to screen readers
//
// See: https://a11yproject.com/posts/how-to-hide-content/
// See: https://hugogiraudel.com/2016/10/13/css-hide-and-seek/

@mixin sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
```

**Comment by jasononeil** [comment]
Fixed by #2200
