### ISSUE TITLE
What's an Onboarding modal?

### ISSUE THREAD

**Issue by didoesdigital** [cultureamp/kaizen-design-system#746]
We've begun fleshing out an onboarding modal concept. It needs a finalised design in the UI Kit and documentation to match. When that exists, we should review the workflow page documentation including these previous feedback about workflows:

**1.** It would be good to have some clarity on when to use this pattern vs. some other patterns that are starting to emerge. For example, the one-click onboarding surveys experience is a multi-step, workflow-esque flow that takes place inside a modal. Do we need guidelines around when we should use this existing workflow pattern and when we can divert from it? 

**2.** I know there are "new feature" and "onboarding" patterns that are starting to appear. We should include guidance about when to use this particular pattern vs. when to use a more traditional "here's what's new" piece, once we actually have that - I can see a lot of similarity between the stepped featureset of these two pieces, and confusion around when to use either one.

_Originally posted by @lindsey-collins in https://github.com/cultureamp/kaizen-design-system/pull/703#issuecomment-671657797_

**Comment by lloydstubber** [comment]
Moved into discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1875)
