### ISSUE TITLE
Tag is missing the "profile" variant

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#790]
![image (28)](https://user-images.githubusercontent.com/1621182/93952475-45695080-fd8c-11ea-9bd5-cfcd3da18466.png)

storybook: https://cultureamp.design/storybook/?path=/story/tag-react--default-medium-kaizen-site-demo
UI Kit: https://www.figma.com/file/GMxm8rvDCbj0Xw3TQWBZ8b/Zen-UI-Kit?node-id=1929%3A29917

**Comment by katsambarcus** [comment]
@NatalieLoyzaga, I had a look at the Profile tag. Looks pretty accurate to the Figma file, but there are a couple of small things I’d like to adjust.

In the UI Kit, the left and right padding was set to 6px, but this was causing some uneven spacing around the edges of the tag and the avatar. I suggest we change to 3px (I'll update Figma to do the same).

![image](https://user-images.githubusercontent.com/15222341/144178121-1b8ac0f4-711b-4131-9ac0-1989c94acc1d.png)


Also, there's something funky happening with the clear icon in Storybook. A strange discolouration behind the icon, which is creating another square. See below image

![image](https://user-images.githubusercontent.com/15222341/144178216-f0db638a-e87c-49d5-9879-9532361f7a64.png)

Let me know if anything is unclear or you have any other questions.

**Comment by NatalieLoyzaga** [comment]
@katsambarcus I have updated the padding and removed the weird square - From what I can tell that was used to add a white bg for the x on the button. I have replaced the icon to use the -white version instead.
