### ISSUE TITLE
Markdown headings don't have IDs so can't be linked to

### ISSUE THREAD

**Issue by sebpearce** [cultureamp/kaizen-design-system#8]
We need to decide whether to:
1) generate dynamic IDs in `snake-case` based on the heading text, or
2) use fixed IDs that are unrelated to the text

**Comment by dougmacknz** [comment]
I can take this one on. I just spoke to @didoesdigital about the options above, we reckon dynamic IDs would probably be the best, in case things change quite heavily and then you've got a URL that takes you somewhere that doesn't make sense anymore.
