### ISSUE TITLE
Coloured backgrounds are not showing by default for "reversed" stories which means the components are invisible

### ISSUE THREAD

**Issue by sebpearce** [cultureamp/kaizen-design-system#81]
![2019-10-25 12 51 00](https://user-images.githubusercontent.com/6406263/67537582-c442ad00-f727-11e9-835f-d8c5a20d2db3.gif)

![image](https://user-images.githubusercontent.com/6406263/67537568-ad9c5600-f727-11e9-8988-11de8aa823d0.png)

PR link: https://github.com/cultureamp/kaizen-design-system/pull/61/commits/c1fd2b4f74be27792ce9c3fcd1f39884c4018daa

**Comment by ActuallyACat** [comment]
This seems to be resolved now, so I'm closing this issue. For future reference, this is how you can set background colours on reversed components:

```
export const ReversedDefault = () => <Button label="Label" reversed={true} />

ReversedDefault.story = {
  name: "Reversed, Default",
  parameters: {
    backgrounds: [
      {
        name: "Wisteria 700",
        value: colorTokens.kz.color.wisteria[700],
        default: true,
      },
    ],
  },
}
```
