### ISSUE TITLE
Clear separations of responsibilities for Select and Autocomplete/Combobox

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#879]
With the plan to consolidate form components into `draft-form`, it's clear we're missing a select component. A basic and accessible select, operating as a thin wrapper over `<select>` with no autocomplete/search functionality should be built in `draft-form`. The current "select" component operates more closely to a autocomplete or a combobox and should be renamed (pending discussion with the design-oriented folks). 

This change may be prone to confuse some folks, the documentation and communication part of this change is just as important as building the missing component.

cc/ @dougmacknz @sebpearce

**Comment by lloydstubber** [comment]
Moved into a discussion [here](https://github.com/cultureamp/kaizen-design-system/discussions/1874)
