### ISSUE TITLE
TextArea and ToggleSwitch have no unit tests

### ISSUE THREAD

**Issue by dougmacknz** [cultureamp/kaizen-design-system#911]
All of our other form primitives have Jest tests except for these two. A recent refactor of TextArea resulted in an incident, which would have been easily caught by unit tests.

**Comment by ActuallyACat** [comment]
@dougmacknz Do you recall the incident that prompted this ticket? From memory, it was something about a defaultValue not being reflected in the component - does that sound correct?

**Comment by dougmacknz** [comment]
This was the fix for it https://github.com/cultureamp/kaizen-design-system/pull/901, basically I broke `defaultValue`
