### ISSUE TITLE
Missing favicon on website. 

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#96]
If a favicon.ico is provided in the root of the site this problem disappears :) 

There will need to be a decision about whether there's a Kaizen-specific branding or whether it's okay to use the Enso icon from the main website.

**Comment by didoesdigital** [comment]
Here are some examples of design systems that use custom favicons/logos:

- https://material.io/design/
- https://feelix.myob.com/
- https://clarity.design/documentation
- https://designsystem.digital.gov/components/

**Almost every other design system I've seen uses their product's logo as their favicon.**

We can use the Culture Amp Enso logo (in Chip form is appropriate) from the UI Kit as the favicon. 
![Enso](https://user-images.githubusercontent.com/2476974/68000382-f61dbb80-fcb3-11e9-9bd1-c3c3d0d1f39c.png)
