### ISSUE TITLE
Same-named type vs const end up with incorrect export

### ISSUE THREAD

**Issue by makenosound** [cultureamp/kaizen-design-system#969]
https://github.com/cultureamp/kaizen-design-system/blob/0e954e3e42c6fd56ab19025a93a850732e01e714/draft-packages/form/KaizenDraft/Form/RadioGroup/RadioGroup.tsx#L39

I’m using the 3.x version of `draft-form` in a project and my build was getting all confused because TypeScript is resolving the value of this default export as the `type RadioGroup` defined _first_ rather than the `const RadioGroup` that we want it to be.

**Comment by dougmacknz** [comment]
Note for advocate pairing: rather than just fixing this one case - we should do a full sweep to check for any other cases of this.
