### ISSUE TITLE
Modal content should be centered

### ISSUE THREAD

**Issue by jasononeil** [cultureamp/kaizen-design-system#971]
Our modal designs have centered content in the modal body, but the component does not do this.

Amusingly, all of the storybook stories added a `<div style={{align: center}}>` to the modal body rather than fixing the component :joy:

**Comment by sebpearce** [comment]
We can make this change for some variants, like the Confirmation Modal, but for others, the body could contain things that would almost certainly break if we added `text-align: center`:

![2021-02-15 16 13 12](https://user-images.githubusercontent.com/6406263/107907914-f7f2b780-6fa8-11eb-90a6-0333549101ef.gif)

In the Input-Edit Modal above, the form elements are passed in as children so the component is agnostic to what goes in its body.

We could
1. still proceed with this and make it a breaking change, or
- try to avoid breakages by adding our own nested selectors for things like `label` and fixing the alignment.

**Comment by mbylstra** [comment]
I think option 3 is the best (for variants other than Confirmation/Roadblock ). Even if most of the elements will want to be centered, this should be opt-in, not opt-out (which the consumer would have to do for input labels). I don't like the idea of having to opt out of magically inherited stuff! (I can imagine a future where we have very sophisticated constraints at a code level on how things are centered but I think we're a long way off from that, and I'm not a fan of doing this with CSS selectors which is a just a form of inheritance/magic to me)

If people are needing to wrap text in an inline style like `<div style={text-align: center}>...</div>`, that is pretty gross. I wonder if there's a way we can make centering simpler and more consistent? Either a `centered` prop to our Paragraph component ) or a tailwind style CSS class? 🤔

**Comment by sebpearce** [comment]
Yeah, I'm leaning towards your view too. If the body was a consistent type of thing rather than a misc bucket, I'd feel better about it being opt-out with centering.

The prop is a good idea! It has the downside of not automatically fixing anyone's centering, but the upside of being a cleaner way to opt in.

**Comment by jasononeil** [comment]
My thoughts:

- I think the `Confirmation` variant is pretty safe to center, I'd be up for making that change. I might explore just _how_ breaking it would be (how many places are using anything other than a paragraph)
- The `Information` variant is left aligned in UI Kit, and has the image off to the side, so that should stay as is.
- The `InputEdit` variant has the problem you mentioned. I'd be open to either suggest (2) (Fix the labels in Kaizen to be left aligned) or (3) Let consumers worry about it.

I created the issue because of this:

>If people are needing to wrap text in an inline style like `<div style={{text-align: center}}>...</div>`, that is pretty gross. 

All of the stories has this exact snippet :D

**Comment by jasononeil** [comment]
In one example repo, 18 ConfirmationModals all have either `<div style={{text-align: center}}>...</div>` or `<div className={styles.someClassThatCenters}>...</div>`

In the same repo, there are 6 InputEditModals, and 5 of them are left aligned, only one is centered.

**Comment by jasononeil** [comment]
After talking with designers, it sounds like we're unsure we want to keep these centered in future. I'm going to close this issue now and wait until future designs are more well known.
