### ISSUE TITLE
Feature request: have branch preview links added as a comment on PRs

### ISSUE THREAD

**Issue by jasononeil** [cultureamp/kaizen-design-system#979]
I've recently got this working for Performance UI:

https://github.com/cultureamp/performance-ui/pull/2651/commits/8215ba810c3401eddeb2df4e4d30e14baae29925

**Comment by ActuallyACat** [comment]
Closed in https://github.com/cultureamp/kaizen-design-system/pull/981 (Thanks @jasononeil!)
