### ISSUE TITLE
Deprecate @kaizen/draft-dropdown-menu

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#991]
@kaizen/draft-menu succeeds this component.

**Comment by sebpearce** [comment]
`draft-dropdown-menu` is currently being used in the following repos:

![image](https://user-images.githubusercontent.com/6406263/107171689-800c1680-6a17-11eb-93db-f995dea6e0d8.png)

**Comment by ActuallyACat** [comment]
This should be moved to legacy-packages, until we're sure that no consumers are using it

**Comment by mbylstra** [comment]
I will look into removing the usage of @kaizen/draft-dropdown-menu from the employee-imports repo that my team owns. If that's easy, then we can just remove the package without needing to move it to legacy-packages.

I think we need to be a bit careful with mentioning private repos here. It's super unlikely any one outside of CA would be following this issue, but still, that list of repos is currently public.

**Comment by mbylstra** [comment]
`@kaizen/draft-drop-menu` (used by employee-imports) contains an elm version but `@kaizen/draft-menu` doesn't. Here's a few different things we could do:

A. Create an Elm version in `@kaizen/draft-menu`. Probably not worth the effort if Elm is contained + could be a lot of effort.
B. Move it into deprecated-packages. Still not ideal, as you run into the problem where you search for "Menu" in the codebase and it shows up so it's a still a bit confusing.
C. Remove it completely from Kaizen and fork the existing @kaizen/draft-dropdown-menu into the employee-imports repo. One day replace with (...insert future solution here... Stencil? Rewrite the whole app in React?).

I'm leaning towards option C unless anyone has any objections!

**Comment by sebpearce** [comment]
@mbylstra I agree with you that C is probably the way to go 👍

**Comment by mbylstra** [comment]
fixed in https://github.com/cultureamp/kaizen-design-system/pull/1044
