### ISSUE TITLE
Badge has a variant that does not exist in UI Kit

### ISSUE THREAD

**Issue by ActuallyACat** [cultureamp/kaizen-design-system#994]
Context: https://github.com/cultureamp/kaizen-design-system/pull/972#issuecomment-771218808

It seems the `dark` variant was erroneously added instead of using the provided `reversed` variant.

**Comment by sebpearce** [comment]
It looks like this was added in #762, which I approved 😅 

This PR was for a usage of the Badge that was not covered in the UI Kit: having a Badge sitting inside a primary Button (see [PR link](https://github.com/cultureamp/kaizen-design-system/pull/762)).

The background colours in the screenshots below show that Default has an opaque bg colour while Dark has a transparent one. My guess would be that the Default variant did not pass design review as Ash on Seedling and it was changed to be transparent black instead.

![image](https://user-images.githubusercontent.com/6406263/107163470-c18fc800-69fd-11eb-86ca-877af97f8a95.png)
![image](https://user-images.githubusercontent.com/6406263/107163481-d4a29800-69fd-11eb-8d45-4da1a7eab3d4.png)

**Comment by sebpearce** [comment]
We should probably clarify for the work is if we've put this in `Selected for work`. It could be that nothing needs to be done here other than letting @katsambarcus know about why the "Dark" variant exists.

**Comment by ActuallyACat** [comment]
@katsambarcus We discussed this, and think that the dark variant can use blue-500 with white text. Link to the variant we should replace it with: https://www.figma.com/file/eZKEE5kXbEMY3lx84oz8iN/%E2%9D%A4%EF%B8%8F-UI-Kit-Heart?node-id=1929%3A14398

**Comment by sebpearce** [comment]
OK no worries. I see it's called "active" in Figma... it'll be a breaking change, but then again it's a significant visual change anyway so I guess it could all happen in one go 👍
